### ISSUE TITLE
rhn server registration

### ISSUE THREAD

**Issue by christopherkrull** [sguyennet/terraform-vsphere-kubespray#12]
Is there a way to specify an internal rhn server to register the servers against?

**Comment by sguyennet** [comment]
Hi,

I just updated the code to support rh_subscription_server and rh_unverified_ssl parameters.
The rh_subscription_server default to subscription.rhsm.redhat.com.

I don't have an internal RHN server so please let me know if it works or if you need extra parameters.

Regards,

Simon.

**Comment by christopherkrull** [comment]
So I tested this, it does not work with subscription-manager. I think I need to use the rhn_register ansible module. Still plugging away.

**Comment by sguyennet** [comment]
Hi,
I just deployed a RHEL satellite 6.5 to test against and it is working fine.
This is what I specified as parameter:
rh_subscription_server = "my_satellite_fqdn/**rhsm**"
rh_unverified_ssl = "true"

**Comment by sguyennet** [comment]
You also have to enable the extra repository on your satellite.

**Comment by christopherkrull** [comment]
That will work
