### ISSUE TITLE
terraform destroy

### ISSUE THREAD

**Issue by christopherkrull** [sguyennet/terraform-vsphere-kubespray#13]
so when running the terraform destory command it gets to the ansible playbook for remove-node in the ansible/kubespray directory and errors out.
command executed
cd ansible/kubespray && ansible-playbook -i ../config/hosts_remove_2.ini -b -u k8s -e 'ansible_ssh_pass=************ ansible_become_pass=*********** delete_nodes_confirmation=yes' -v remove-node.yml

The reason is it is calling the inventory file only one directory higher when it should be ../../config/hosts_remove*.ini

**Comment by sguyennet** [comment]
Thanks a lot for reporting this issue. I just fixed it.
