### ISSUE TITLE
Installation of K8 custer fails

### ISSUE THREAD

**Issue by ghost** [sguyennet/terraform-vsphere-kubespray#15]
Hi Simon,
first thanks for great posts.
I have been trying to install  k8 cluster for the past few days but keep failing with the following error, 

"* null_resource.kubespray_create: Error running command 'cd ansible/kubespray && ansible-playbook -i ../../config/hosts.ini -b -u terra -e 'ansible_ssh_pass=mavenir ansible_become_pass=mavenir kube_version=v1.12.5' -T 300 -v cluster.yml': exit status 2. Output: column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}
fatal: [k8srv-worker-0]: FAILED! => {"reason": "'delegate_to' is not a valid attribute for a TaskInclude\n\nThe error appears to be in '/home/terra/terraform-vsphere-kubespray/ansible/kubespray/roles/download/tasks/download_container.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: container_download | Make download decision if pull is required by tag or sha256\n  ^ here\n"}"

Client machine and template create according to your instaructions.

ansible --version :
<i>ansible 2.8.1
  config file = None
  configured module search path = [u'/home/terra/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/terra/.local/lib/python2.7/site-packages/ansible
  executable location = /home/terra/.local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]</i>

help is appriciated.

Thanks, Avi

**Comment by sguyennet** [comment]
The new version of Ansible is not supported yet. Please downgrade to the version 2.7.11 for the moment.
Regards,
Simon.
