### ISSUE TITLE
No such file or directory during "kubeadm"

### ISSUE THREAD

**Issue by tdovan** [sguyennet/terraform-vsphere-kubespray#16]
vm creation is ok.
if fails to copy  the kubeadm during the task: "download : kubeadm | Copy kubeadm binary from download dir" with the following error:

TASK [download : kubeadm | Copy kubeadm binary from download dir] **************
Tuesday 16 July 2019  09:16:33 +0200 (0:00:01.932)       0:05:29.185 **********
fatal: [k8s-kubespray-master-0 -> 192.168.1.161]: FAILED! => {"changed": false, "cmd": "sshpass", "msg": "[Errno 2] No such file or directory", "rc": 2}

and /tmp/release is ok:

# ll /tmp/releases/
total 290144
-rwxr-xr-x. 1 root root  30863968 Jul 16 07:55 calicoctl
-rwxr-xr-x. 1 root root  15385105 Jul 16 07:55 cni-plugins-amd64-v0.6.0.tgz
-rwxr-xr-x. 1 root root 211257536 Jul 16 07:55 hyperkube
-rwxr-xr-x. 1 root root  39591200 Jul 16 07:55 kubeadm

**Comment by itsecforu** [comment]
did u fix it?

**Comment by tdovan** [comment]
yep thanks. it was a ansible.cfg param os a sshpass config issue. thanks

**Comment by paltaa** [comment]
@tdovan what was the fix ?
