### ISSUE TITLE
Terraform fails waiting for IP

### ISSUE THREAD

**Issue by ebbeelsborg** [sguyennet/terraform-vsphere-kubespray#17]
First of all: Thanks for making the TF and the guide available; it looks just like the thing I'm looking for.

I've followed the blog post very closely, but Terraform fails when applying:

> Error: timeout waiting for an available IP address
>
> on vsphere-kubespray.tf line 556, in resource "vsphere_virtual_machine" "haproxy":
> 556: resource "vsphere_virtual_machine" "haproxy" {
>
>
>
> Error: error cloning virtual machine: A general system error occurred: internal error
>
>  on vsphere-kubespray.tf line 556, in resource "vsphere_virtual_machine" "haproxy":
> 556: resource "vsphere_virtual_machine" "haproxy" {

VMs can be created successfully and receive IPs via DHCP. I've tried some combinations of TF options as mentioned in https://github.com/terraform-providers/terraform-provider-vsphere/issues/718, but without luck.

Any ideas? What info would you need?

We're using ESXi 6.7 and VMWare Tools 10304 (Guest Managed).

**Comment by ebbeelsborg** [comment]
I managed to work around it; it required a small tweak to the TF because of our vSphere setup. Closing this issue.

**Comment by nicosma** [comment]
Hi,

I have the same issue. Could you share what is the tweak that you performed ?

Thanks!

**Comment by yomofo2s** [comment]
Hello I also have the similar issue. It would be nice to have the workaround. 

![Screenshot 2021-04-18 150014](https://user-images.githubusercontent.com/44329653/115146456-e1271a80-a056-11eb-9685-483183fa81cd.png)
