### ISSUE TITLE
upgrade kubernetes version to v1.15

### ISSUE THREAD

**Issue by zcohen331** [sguyennet/terraform-vsphere-kubespray#18]

**Comment by zcohen331** [comment]
Hello Simon.
How's going, We discussed in the past about some issue with K8S via terraform at  vmware..
I'm going now to install from scratch K8S single , (1 master & 1 worker).
First question is if I can to install single without haproxy vm ?
Second question, What is required to change in the terraform installation in order to support  kubernetes 1.15.x version?
Your assistance will be very appreciated. 
Thanks

**Comment by zcohen331** [comment]
Hello Simon.
I hope u already see my questions?
Because I think I accidentally closed the issue.
Thanks

**Comment by zcohen331** [comment]
Hello Simon,
I finished to install the K8S single with below version:
k8s_kubespray_version = "v2.10.3"
k8s_version = "v1.14.3"
I did change them to new version for kubernetes upgrade:
k8s_kubespray_version = "v2.10.4"
k8s_version = "v1.15.0"
and I upgrade failed, My question is , The terraform is support to new below version?
Thanks

**Comment by sguyennet** [comment]
Hi,
You don't need the HAProxy VMs as you will have only one master, but for this you will have to modify the Terraform script slightly.
Kubespray doesn't support Kubernetes 1.15.0. As this Terraform script depends on Kubespray, you will have to wait for a new Kubespray release.
Regards,
Simon.

**Comment by zcohen331** [comment]
Hello,
Thanks for reply and updating.
But If I remove HAProxy parameters from terraform.tfvars file the installation failed .
How can I install without HAProxy VM?
Thanks

**Comment by zcohen331** [comment]
Hello Simon,
Following your statement:
_"You don't need the HAProxy VMs as you will have only one master, but for this you will have to modify the Terraform script slightly"_
Is there a single on/off flag that controls the usage of HAProxy instead of going and changing the installation scripts in many places?
Thanks a lot 
Zion
