### ISSUE TITLE
Could not find or access 'vsphere-cloud-config.j2'

### ISSUE THREAD

**Issue by funky81** [sguyennet/terraform-vsphere-kubespray#2]
This script will having message like this either on Ubuntu or Centos.
This is because of this there's problem code ([kubespray version 2.6](https://github.com/kubernetes-incubator/kubespray/issues/3082)) is looking for the "{{ cloud_provider }}-cloud-config.j2" template file that was moved during  on 4/2/2018 

solutions 
Delete this part on https://github.com/kubernetes-incubator/kubespray/blob/master/roles/kubernetes/node/tasks/main.yml

> name: Write cloud-config
> template:
> src: "{{ cloud_provider }}-cloud-config.j2"
> dest: "{{ kube_config_dir }}/cloud_config"
> group: "{{ kube_cert_group }}"
> mode: 0640
> when:
> inventory_hostname in groups['k8s-cluster']
> cloud_provider is defined
> cloud_provider in [ 'openstack', 'azure', 'vsphere' ]
> tags:
> cloud-provider

**Comment by sguyennet** [comment]
Hi,

I didn't had the chance to play with Kubespray 2.6 yet, but this issue sound like a Kubespray issue not a Terraform one. Thanks for the info anyway, I will try to test the new Kubespray soon.

Thanks,

Simon.

**Comment by funky81** [comment]
Yup, it's kubespray issue. I can confirm about that
