### ISSUE TITLE
getting error com.vmware.vapi.rest.httpNotFound while folder creation

### ISSUE THREAD

**Issue by amolsh** [sguyennet/terraform-vsphere-kubespray#3]
Hi @sguyennet , I am using this repo to create lab cluster. I am facing 1 issue.
vsphere version:6.5
While creating folder it throws following error, but folder is getting created:

Error: Error refreshing state: 1 error(s) occurred:

* vsphere_folder.folder: 1 error(s) occurred:

* vsphere_folder.folder: vsphere_folder.folder: error reading tags: Get unexpected status code: 404: call failed: Error response from vCloud Suite API: {"name":"com.vmware.vapi.rest.httpNotFound","localizableMessages":[{"defaultMessage":"Not found.","id":"com.vmware.vapi.rest.httpNotFound"}],"majorErrorCode":404} 

I am not sure weather it is vsphere 6.5 version issue, as it says api not found or permission issue.
If you are aware of any such scenario, can you please help me figure out this?

**Comment by sguyennet** [comment]
Hi,
What is your exact version of your vCenter?
(click on your vCenter at the top of your inventory. You should find the build in the summary tab).
Thanks,
Simon.

**Comment by amolsh** [comment]
Thanks for quick response!
This is exact version info:
vSphere Web Client  Version 6.5.0.20000 Build 8815520  
VMware ESXi, 6.5.0, 8935087
Terraform version: Terraform v0.11.7

**Comment by amolsh** [comment]
I am closing this an it is working with another DC in my vcenter, I am not sure what was issue with my previous DC.
