### ISSUE TITLE
Extra ansible argument 'ansible_become_method=su' not working on debian

### ISSUE THREAD

**Issue by bbichero** [sguyennet/terraform-vsphere-kubespray#31]
I saw that you have added an extra argument for ansible-playbook, only when Operating System is Debian, why ?
https://github.com/sguyennet/terraform-vsphere-kubespray/blob/b5aaf69c3fe6420c19a9e2b960fc04d2024e9ec7/vsphere-kubespray.tf#L223
This argument produce error when ansible role `haproxy` run:
```
Incorrect su password
```
If I remove it, playbook run perfectly

**Comment by sguyennet** [comment]
Hi,
I added this parameter because out of the box on a Debian 9 there is no sudo, therefor we need to use su to gain root privilege.
If your image of Debian is using sudo, then you should remove this parameter.

**Comment by bbichero** [comment]
Thanks for the quick answer, okay I understand.
